sonar.projectKey=Lorris_Securisation_des_applications
sonar.organization=lorris

# Dossier source à analyser
sonar.sources=backend
sonar.sources=frontend

# Exclusions nécessaires
sonar.exclusions=**/node_modules/**